version: '3'

services:
  node1:
    build: .
    ports:
      - "8001:8000"

  node2:
    build: .
    ports:
      - "8002:8000"

  node3:
    build: .
    ports:
      - "8003:8000"
